export const fontFamily = {
	// https://modernfontstacks.com
	antique: [
		"Superclarendon",
		"Bookman Old Style",
		"URW Bookman",
		"URW Bookman L",
		"Georgia Pro",
		"Georgia",
		"serif",
	],
	transitional: [
		"Charter",
		"Bitstream Charter",
		"Sitka Text",
		"Cambria",
		"serif",
	],
	"old-style": [
		"Iowan Old Style",
		"Palatino Linotype",
		"URW Palladio L",
		"P052",
		"serif",
	],
	humanist: [
		"Seravek",
		"Gill Sans Nova",
		"Ubuntu",
		"Calibri",
		"DejaVu Sans",
		"source-sans-pro",
		"sans-serif",
	],
	"humanist-geometric": [
		"Avenir",
		"Montserrat",
		"Corbel",
		"URW Gothic",
		"source-sans-pro",
		"sans-serif",
	],
	"humanist-classical": [
		"Optima",
		"Candara",
		"Noto Sans",
		"source-sans-pro",
		"sans-serif",
	],
	"neo-grotesque": [
		"Inter",
		"Roboto",
		"Helvetica Neue",
		"Arial Nova",
		"Nimbus Sans",
		"Arial",
		"sans-serif",
	],
	"mono-serif": ["Nimbus Mono PS", "Courier New", "monospace"],
	industrial: [
		"Bahnschrift",
		"DIN Alternate",
		"Franklin Gothic Medium",
		"Nimbus Sans Narrow",
		"sans-serif-condensed",
		"sans-serif",
	],
	"serif-slab": [
		"Rockwell",
		"Rockwell Nova",
		"Roboto Slab",
		"DejaVu Serif",
		"Sitka Small",
		"serif",
	],
	"sans-rounded": [
		"ui-rounded",
		"Hiragino Maru Gothic ProN",
		"Quicksand",
		"Comfortaa",
		"Manjari",
		"Arial Rounded MT",
		"Arial Rounded MT Bold",
		"Calibri",
		"source-sans-pro",
		"sans-serif",
	],
	didone: [
		"Didot",
		"Bodoni MT",
		"Noto Serif Display",
		"URW Palladio L",
		"P052",
		"Sylfaen",
		"serif",
	],
	handwritten: [
		"Segoe Print",
		"Bradley Hand",
		"Chilanka",
		"TSCu_Comic",
		"casual",
		"cursive",
	],
};
